# Generated by Django 4.2.13 on 2024-07-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_excerpt_event_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_on']},
        ),
    ]
