# Generated by Django 4.2.14 on 2024-07-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
    ]
