# Generated by Django 4.2.14 on 2024-07-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
