# Generated by Django 4.2.14 on 2024-08-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
